src: https://dse-static-oai-pmh.acdh-dev.oeaw.ac.at/
maintainer: mzoltak@oeaw.ac.at
outputDir: data
# verticals tags mapping schema
tags:
  chapter:
  - doc
  paragraph:
  - imprimatur
  - head
  - annotationBlock
  - connecteds
  - u
# paths used in the corpora configuration file
# keep them like that for the compatibility with the compile_corp.sh
basePath:
  data: /var/lib/manatee/data
  vertical: /var/lib/manatee/registry
# udppipe or spacy
backend: udppipe
# languages reported by the src endpoint to (No)Sketch Engine langages conversion
langMap:
  ara: Arabic
  deu: German
  ger: German
  eng: English
  ita: Italian
  lat: Latin
udppipe:
  apiUrl: https://lindat.mff.cuni.cz/services/udpipe/api/process
  # languages as reported by the src endpoint
  models:
    ara: arabic-padt-ud-2.15-241121
    deu: german-hdt-ud-2.15-241121
    ger: german-hdt-ud-2.15-241121
    eng: english-partut-ud-2.15-241121
    ita: italian-partut-ud-2.15-241121
    lat: latin-llct-ud-2.15-241121
spacy:
  # languages as reported by the src endpoint
  models:
    deu: de_dep_news_trf
    ger: de_dep_news_trf
    eng: en_core_web_trf
    ita: it_core_news_lg
    lat: it_core_news_lg
# a static part of the (No)Sketch Engine corpora config file
corporaConfig: |
  ENCODING "UTF-8"
  ATTRIBUTE word
  ATTRIBUTE lemma
  ATTRIBUTE pos
  ATTRIBUTE lc {
    DYNAMIC    utf8lowercase
    DYNLIB     internal
    ARG1       "C"
    FUNTYPE    s
    FROMATTR   word
    TYPE       index
    TRANSQUERY yes
  }
  ATTRIBUTE orth {
    DYNAMIC    utf8lowercase
    DYNLIB     internal
    ARG1       "C"
    FUNTYPE    s
    FROMATTR   word
    TYPE       index
    TRANSQUERY yes
  }
  ATTRIBUTE norm {
    DYNAMIC    utf8lowercase
    DYNLIB     internal
    ARG1       "C"
    FUNTYPE    s
    FROMATTR   word
    TYPE       index
    TRANSQUERY yes
  }
  ATTRIBUTE phonetic {
    DYNAMIC    utf8lowercase
    DYNLIB     internal
    ARG1       "C"
    FUNTYPE    s
    FROMATTR   word
    TYPE       index
    TRANSQUERY yes
  }
  STRUCTURE doc {
    ATTRIBUTE LandingPageURI
  }
  STRUCTURE chapter {
    ATTRIBUTE ID
    ATTRIBUTE LandingPageURI
  }
  STRUCTURE p
  STRUCTURE s
  STRUCTURE g {
   DISPLAYTAG 0
   DISPLAYBEGIN "_EMPTY_"
  }
