name: build
on:
  workflow_dispatch: ~
  release:
    type: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: clone and config mquery-sru
      run: |
        git clone https://github.com/czcorpus/mquery-sru.git
        cp config.json mquery-sru/conf-docker.json
        cp confgen.py corpora.yaml mquery-sru/
        cp searchrt.go mquery-sru/handler/v20/searchrt.go
        cp rscrr.go mquery-sru/result/rscrr.go
        cp result.go mquery-sru/result/result.go
        cat preDockerfile mquery-sru/Dockerfile postDockerfile > tmp && mv tmp mquery-sru/Dockerfile
    - name: docker build
      run: docker build -t acdhch/noske-fcs --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" mquery-sru
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push acdhch/noske-fcs


