name: dse-static
on:
  workflow_dispatch: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: extract existing data
      run: |
        cd dse-static-pipeline
        ./extract_existing.sh
    - name: create missing verticals
      run: |
        cd dse-static-pipeline
        python3 -m venv env
        source env/bin/activate
        pip3 install -U -r requirements.txt
        python3 create_verticals.py -c config_sample.yaml -s
    - name: compile corpora
      run: |
        cd dse-static-pipeline
        ./compile_corp.sh
    - name: build updated image
      run: |
        cd dse-static-pipeline
        ./build_image.sh
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push acdhch/noske-fcs-dse-static:latest


