name: dse-static
on:
  workflow_dispatch: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: extract existing data
      run: |
        cd dse-static-pipeline
        mkdir data
        docker pull acdhch/noske-fcs-dse-static:latest
        docker save acdhch/noske-fcs-dse-static:latest > tmp.tar
        for i in `docker image inspect acdhch/noske-fcs-dse-static:latest | grep -A 6 RootFS | grep sha256 | sed -e 's/ *"sha256://' -e 's/".*//'`; do
          tar -xf tmp.tar --transform 's/.*\///' blobs/sha256/$i
          tar -xf $i -C data --transform 's/.*\/registry\///' --wildcards var/lib/manatee/registry/* 2>/dev/null || true
          rm $i
        done
        rm tmp.tar
    - name: create missing verticals
      run: |
        cd dse-static-pipeline
        python3 create_verticals.py -c config_sample.yaml -s
    - name: compile corpora
      run: |
        cd dse-static-pipeline
        ./compile_corp.sh
    - name: build updated image
      run: |
        cd dse-static-pipeline
        ./build_image.sh
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push acdhch/noske-fcs-dse-static:latest


